services:
  - type: web
    name: sudoku-engine
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: LOG_LEVEL_ROOT
        value: INFO
      - key: LOG_LEVEL_APP
        value: INFO
